"""
Evolution module for Mad Spark Alt.

This module implements genetic algorithms for evolving and optimizing ideas
generated by the QADI thinking agents.
"""

from mad_spark_alt.evolution.cached_fitness import CachedFitnessEvaluator
from mad_spark_alt.evolution.checkpointing import (
    EvolutionCheckpoint,
    EvolutionCheckpointer,
)
from mad_spark_alt.evolution.fitness import FitnessEvaluator
from mad_spark_alt.evolution.genetic_algorithm import GeneticAlgorithm
from mad_spark_alt.evolution.interfaces import (
    EvolutionConfig,
    EvolutionRequest,
    EvolutionResult,
    GeneticOperatorInterface,
    PopulationSnapshot,
    SelectionStrategy,
)
from mad_spark_alt.evolution.operators import (
    CrossoverOperator,
    EliteSelection,
    MutationOperator,
    RandomSelection,
    RankSelection,
    RouletteWheelSelection,
    TournamentSelection,
)

__all__ = [
    # Interfaces
    "EvolutionRequest",
    "EvolutionResult",
    "GeneticOperatorInterface",
    "SelectionStrategy",
    "PopulationSnapshot",
    "EvolutionConfig",
    # Core Components
    "GeneticAlgorithm",
    "FitnessEvaluator",
    "CachedFitnessEvaluator",
    "EvolutionCheckpoint",
    "EvolutionCheckpointer",
    # Operators
    "CrossoverOperator",
    "MutationOperator",
    "TournamentSelection",
    "EliteSelection",
    "RouletteWheelSelection",
    "RankSelection",
    "RandomSelection",
]
